config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root 'entries#index'

  resources :foods
  resources :entries
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entry.rb
# frozen_string_literal: true

# represents a food (and quantity of that food) eaten by a user at a given time
class Entry < ApplicationRecord
  belongs_to :food
  belongs_to :user
  validates :quantity, numericality: { greater_than: 0 }
end

# == Schema Information
#
# Table name: entries
#
#  id          :integer          not null, primary key
#  consumed_at :datetime
#  quantity    :float            default(1.0)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  food_id     :integer          not null
#  user_id     :integer          not null
#
# Indexes
#
#  index_entries_on_food_id  (food_id)
#  index_entries_on_user_id  (user_id)
#
# Foreign Keys
#
#  food_id  (food_id => foods.id)
#  user_id  (user_id => users.id)
#

app/models/food.rb
# frozen_string_literal: true

class Food < ApplicationRecord
end

# == Schema Information
#
# Table name: foods
#
#  id         :integer          not null, primary key
#  name       :string
#  unit_name  :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

app/models/user.rb
# frozen_string_literal: true

# a user
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :entries, dependent: :destroy
end

# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/entries_controller.rb
# frozen_string_literal: true

# entries controller
class EntriesController < ApplicationController
  before_action :set_entry, only: %i[show edit update destroy]

  # GET /users/:user_id/entries
  def index
    @entries = current_user.entries
  end

  # GET /users/:user_id/entries/:id
  def show; end

  # GET /users/:user_id/entries/new
  def new
    @entry = current_user.entries.build
  end

  # POST /users/:user_id/entries
  def create
    @entry = current_user.entries.build(entry_params)
    if @entry.save
      redirect_to entries_path, notice: 'Entry was successfully created.'
    else
      render :new
    end
  end

  # GET /users/:user_id/entries/:id/edit
  def edit; end

  # PATCH/PUT /users/:user_id/entries/:id
  def update
    if @entry.update(entry_params)
      redirect_to @entry, notice: 'Entry was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /users/:user_id/entries/:id
  def destroy
    @entry.destroy
    redirect_to entries_path, notice: 'Entry was successfully destroyed.'
  end

  private

  def set_entry
    @entry = current_user.entries.find(params[:id])
  end

  def entry_params
    params.require(:entry).permit(:food_id, :quantity, :consumed_at)
  end
end

app/controllers/foods_controller.rb
# frozen_string_literal: true

class FoodsController < ApplicationController
  before_action :set_food, only: %i[show edit update destroy]

  # GET /foods or /foods.json
  def index
    @foods = Food.all
  end

  # GET /foods/1 or /foods/1.json
  def show; end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # GET /foods/1/edit
  def edit; end

  # POST /foods or /foods.json
  def create
    @food = Food.new(food_params)

    respond_to do |format|
      if @food.save
        format.html { redirect_to food_url(@food), notice: 'Food was successfully created.' }
        format.json { render :show, status: :created, location: @food }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foods/1 or /foods/1.json
  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to food_url(@food), notice: 'Food was successfully updated.' }
        format.json { render :show, status: :ok, location: @food }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1 or /foods/1.json
  def destroy
    @food.destroy

    respond_to do |format|
      format.html { redirect_to foods_url, notice: 'Food was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_food
    @food = Food.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def food_params
    params.require(:food).permit(:name, :unit_name)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/foods_helper.rb
# frozen_string_literal: true

module FoodsHelper
end

app/views/entries/_entry.html.haml
%tr
  %td= entry.food.name
  %td= pluralize(entry.quantity, entry.food.unit_name)
  %td= (entry.consumed_at.presence || entry.created_at).strftime("%B %d, %Y %H:%M")
  %td
    = link_to 'Show', entry
    = link_to 'Edit', edit_entry_path(entry)

app/views/entries/_form.html.haml
= form_with(model: entry) do |form|
  - if entry.errors.any?
    %div{ style: "color: red" }
      %h2.example= pluralize(entry.errors.count, "error") + " prohibited this entry from being saved:"
      %ul
        = entry.errors.each do |error|
          %li= error.full_message
   
  .field
    = form.label :food_id
    = form.collection_select :food_id, Food.all, :id, :name, prompt: "Select a food"

  .field
    = form.label :quantity
    = form.number_field :quantity, step: "any", min: 0.1

  .field
    = form.label :consumed_at
    = form.datetime_local_field :consumed_at, value: DateTime.now.strftime('%Y-%m-%dT%H:%M')

  .actions
    = form.submit

app/views/entries/index.html.haml
%h1 Your Entries

%table
  %thead
    %tr
      %th Food
      %th Quantity
      %th Consumed At
      %th Actions
  %tbody
    - @entries.reverse.each do |entry|
      = render entry

= link_to 'New Entry', new_entry_path

app/views/entries/new.html.haml
%h1 New Entry

= render 'form', entry: @entry

= link_to 'Back', entries_path

app/views/foods/_food.html.erb
<div id="<%= dom_id food %>">
  <p>
    <strong>Name:</strong>
    <%= food.name %>
  </p>

  <p>
    <strong>Unit name:</strong>
    <%= food.unit_name %>
  </p>

</div>

app/views/foods/_form.html.erb
<%= form_with(model: food) do |form| %>
  <% if food.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
        <% food.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :unit_name, style: "display: block" %>
    <%= form.text_field :unit_name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/foods/edit.html.erb
<h1>Editing food</h1>

<%= render "form", food: @food %>

<br>

<div>
  <%= link_to "Show this food", @food %> |
  <%= link_to "Back to foods", foods_path %>
</div>

app/views/foods/index.html.erb
<h1>Foods</h1>

<div id="foods">
  <% @foods.each do |food| %>
    <%= render food %>
    <p>
      <%= link_to "Show this food", food %>
    </p>
  <% end %>
</div>

<%= link_to "New food", new_food_path %>

app/views/foods/new.html.erb
<h1>New food</h1>

<%= render "form", food: @food %>

<br>

<div>
  <%= link_to "Back to foods", foods_path %>
</div>

app/views/foods/show.html.erb
<%= render @food %>

<div>
  <%= link_to "Edit this food", edit_food_path(@food) %> |
  <%= link_to "Back to foods", foods_path %>

  <%= button_to "Destroy this food", @food, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FoodDiary</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <nav>
        <ul>
          <% if user_signed_in? %>
            <li><%= link_to 'Your Entries', entries_path %></li>
            <li><%= button_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to 'Sign In', new_user_session_path %></li>
            <li><%= link_to 'Sign Up', new_user_registration_path %></li>
          <% end %>
        </ul>
      </nav>
    </header>

    <p style="color: green"><%= notice %></p>
    <p class="color: red"><%= alert %></p>
    <%= yield %>
  </body>
</html>